# Generated by Django 4.1 on 2023-11-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='task',
            new_name='taskName',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='taskDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
